### ISSUE TITLE
Ubermenu not replacing collapsed Bootstrap menu

### ISSUE THREAD

**Issue by eSaner** [salcode/bootstrap-genesis#105]
I've installed Ubermenu, which replaces the Bootstrap menu and works as expected until <768px, when the collapsed Bootstrap menu appears in place of Ubermenu.

Also at  <768px, expanding the the Bootstrap menu shows the collapsed Ubermenu button, but the Ubermenu button does not work.

Should this be happening? How can I disable the responsive/collapsed Bootstrap menu?

Ubermenu >=768px:
![ubermenu](https://cloud.githubusercontent.com/assets/6232891/10309234/710e9e26-6c09-11e5-9f5b-28b0637cc1ad.jpg)

Bootstrap menu <768px:
![bootstrap-menu](https://cloud.githubusercontent.com/assets/6232891/10309242/78b786d8-6c09-11e5-9707-e6b07f39cb4d.jpg)

Bootstrap menu expanded <768px:
![bootstrap-menu-expanded](https://cloud.githubusercontent.com/assets/6232891/10309246/7e4a4cca-6c09-11e5-8e3d-8669806f8e43.jpg)

**Comment by salcode** [comment]
@dustyndoyle have you experienced this issue?

**Comment by salcode** [comment]
@eSaner thanks for bringing this to my attention.

It looks like the check introduced in #6 looks for the class `UberMenuStandard`, which is not detecting the latest version of the **UberMenu** plugin.

Changing `UberMenuStandard` to `UberMenu` in this check appears to resolve the problem (this code appears in `lib/nav.php`).  I'd recommend trying this, it resolved the issue in my local install.  Please let me know if this does not resolve the issue for you.

By the way, great bug report, the screenshots were particularly helpful in understanding the problem.

Thanks.

**Comment by eSaner** [comment]
Thanks for the quick response! That fixed it.

**Comment by salcode** [comment]
Awesome, thanks for the follow up :+1:

**Comment by dustyndoyle** [comment]
Yes, I had to change the class to Ubermenu on the latest site I used it for. That fixed it for me, it looks like ubermenu 3 changed their class name
On Oct 6, 2015 10:04 AM, Sal Ferrarello notifications@github.com wrote:@dustyndoyle have you experienced this issue?

**Comment by salcode** [comment]
Thanks @dustyndoyle, this is now resolved in `develop`
