### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by codenameEli** [salcode/bootstrap-genesis#114]
Indentation was not there for meta/head tags. Could be intentional by you, just throwing it out there. PR incoming

**Comment by salcode** [comment]
I'm not sure how I feel about how this affects the rendered markup

Original on the left, your PR on the right

![image](https://cloud.githubusercontent.com/assets/5194588/10983113/d3f2327c-83de-11e5-908d-55fdb807c776.png)

This is an interesting question, do we do indentation based on final rendered markup or source code?

**Comment by salcode** [comment]
My gut is we keep it the way it currently is.

Since there hasn't been any activity on this, I'm going to close this issue.  If this specific issue still exists, we can reopen.  If there is something tangentially related, we can create a new issue.
