### ISSUE TITLE
wrong glyphicons

### ISSUE THREAD

**Issue by brixtee** [salcode/bootstrap-genesis#117]
Hi Sal,

I just wanted to report that the icon used for the search form is incorrect. My version shows a heart. I did some research which seems to suggest that the problem is due to the hierarchy of the font directory relative to root. 

Thanks for the free theme!

**Comment by salcode** [comment]
@brixtee 

I've been unable to recreate this error.

Is it possible you have a plugin activated that is loading a different set of glyphicons?

As a troubleshooting step, I'd disable all plugins and see if you're still getting this behavior.

If you have a public URL I can look at, I'd be happy to take a look at it.

Thanks.

**Comment by salcode** [comment]
Since there hasn't been any activity on this, I'm going to close this issue.  If this specific issue still exists, we can reopen.  If there is something tangentially related, we can create a new issue.

**Comment by brixtee** [comment]
So sorry... you were correct in your original reply. Please forgive me for not replying sooner. Thank you so much for the tip in uncovering the problem. Best wishes!

**Comment by salcode** [comment]
No worries.  I'm glad to hear you got the issue sorted.  All the best.
