### ISSUE TITLE
Should we add CSS clear both to .archive-pagination

### ISSUE THREAD

**Issue by salcode** [salcode/bootstrap-genesis#122]
I find that every time I build a theme I add

```
.archive-pagination { clear: both; }
```

Does it make sense to make this part of the theme by default?

I'm trying to come up with a time when one wouldn't want this and I'm not coming up with anything.

**Comment by bryanwillis** [comment]
Just an idea to avoid extra css

https://github.com/salcode/bootstrap-genesis/pull/124

**Comment by salcode** [comment]
Yes, seems to be the answer.  See #156
