### ISSUE TITLE
Does Bootstrap Genesis need to be updated?

### ISSUE THREAD

**Issue by salcode** [salcode/bootstrap-genesis#147]
@unwiredtech wrote:

> I used your framework last month and it is necessary to update?

**Comment by salcode** [comment]
No, Bootstrap Genesis does not need to be updated when a new version comes up.

I do however recommend you keep the Genesis Framework updated to the latest version.

**Comment by unwiredtech** [comment]
I will check what were your changes in the Genesis side. 

Currently using Genesis 2.2.7.

**Comment by salcode** [comment]
> I will check what were your changes in the Genesis side.

I'm not sure I understand this question.  If you're asking about the changes to Bootstrap Genesis, there is a changelog at https://github.com/salcode/bootstrap-genesis/blob/develop/CHANGELOG.md

> Currently using Genesis 2.2.7.

Good, that is the latest version.

**Comment by salcode** [comment]
@unwiredtech 

Since there hasn't been any further movement on this issue I'm going to assume the CHANGELOG has the information you were looking for.  If this has not answered your question feel free to re-open this issue with further clarification.

Thanks.
