### ISSUE TITLE
JavaScript Vendor Folder not compiling

### ISSUE THREAD

**Issue by salcode** [salcode/bootstrap-genesis#148]
@unwiredtech wrote:

> Javascript Vendor folder is not compiling, I tried to add to folders of JS libaries but they are not being uglified or minified.

**Comment by salcode** [comment]
This sounds similar to the problem described in https://github.com/salcode/bootstrap-genesis/issues/116#issuecomment-156474326

Can you provide more information on the steps to recreate this problem?  Thank you.

**Comment by unwiredtech** [comment]
The issue where that the vendor;
/js/vendor/particle-js/particle.js
/js/vendor/swipebox/swipebox.js
- are not combined with javacript.min.js, I noticed this when the grunt did not change, so I assume that it was not added to the main js, BUT to my surprise both particle-js and swipebox are working.

any thoughts?

**Comment by salcode** [comment]
When you run `grunt` it should include all of the `.js` files in `/vendor` in `javascript.min.js`, this is because of the line https://github.com/salcode/bootstrap-genesis/blob/develop/Gruntfile.js#L58

If these libraries (particle-js and swipebox) are working, it sounds like they are being added to `javascript.min.js`

If I'm misunderstanding and you still feel there is a problem, you may want to create Git repo of the problem and I'll take a look at it.

**Comment by unwiredtech** [comment]
Hi Salcode, Apologies for this late reply. 

I think it is included in the `javacript.min.js` but it seems it is not appearing in grunt when compiling?

I turned over the project and the functionality is working anyway, so no worries.

Kind Regards,

**Comment by salcode** [comment]
@unwiredtech I'm glad you got it sorted.

I'm going to close this issue since the code is appearing in the compiled file.

If you have further questions about how the grunt task works feel free to open a new issue specific to that.

Thanks.
