### ISSUE TITLE
Genesis Child Theme Defaults

### ISSUE THREAD

**Issue by bryanwillis** [salcode/bootstrap-genesis#16]
First, nice theme. I started building my own bootstrap genesis theme, I was shocked to realize yours was the only one out there really. I've been using genesis for about 6 months now after a client made the request. Wish I would have made the switch a long time ago. The semantic markup functions and filters makes it worth it all in itself, in my opinion.   

Anyway, to get to the point, I learned most of what I currently know about it from just browsing through the main theme as well as the enterprise-pro theme.

I always thought child themes were suppose to start with : 

```include_once( get_template_directory() . '/lib/init.php' );```

Is there a reason you don't include that? It looks like by not including that you instead use `genesis_setup`

 

I can't quite figure out why this is or what the benefit of one way of doing things over the other is.

It seems complicated because without using: 

```include_once( get_template_directory() . '/lib/init.php' );```

it appears you have to use `genesis_setup` anytime you want to do anything. Can you explain a little bit why you do it this way? Thanks for your help! I'll be sure to link your theme when I get mine all finished.

**Comment by salcode** [comment]
This modification has been merged into the master branch.  Now functions.php loads all the files in the `/includes` directory on the `genesis_setup` hook at priority __15__.
