### ISSUE TITLE
navbar is not static

### ISSUE THREAD

**Issue by ClintonGallagher** [salcode/bootstrap-genesis#169]
Genesis 2.5.2
Bootstrapped Genesis 0.8.2

navbar-static-top is present in the source but the navbar is not sticky: the navbar scrolls with the page when the page is scrolled.

**Comment by salcode** [comment]
Hi Clinton,

You're correct the default nav for this theme is not sticky, which is the behavior of Bootstrap's static nav. See http://getbootstrap.com/examples/navbar-static-top/

You may have noticed my personal site, https://salferrarello.com/ __does__ have a fixed (a.k.a. sticky) nav. I added this behavior using additional code which I've made available at https://github.com/salcode/bootstrap-genesis-fixed-nav.

I hope that helps. Have a great rest of your weekend.

**Comment by ClintonGallagher** [comment]
Gross oversight on my part. Pun intended, the additional code "fixes" my ignorance.

**Comment by salcode** [comment]
Ha ha, no worries.  I'm glad you got it sorted.

By the way, if you add your site to the [list of sites using Bootstrap Genesis](https://github.com/salcode/bootstrap-genesis/wiki/Bootstrap-Genesis-in-the-Wild) in the Wiki, it would be great to see more sites listed. 😀

**Comment by ClintonGallagher** [comment]
I’ll list the site when its deployed Sal. Your work deserves the recognition

-- Clinton Gallagher
