### ISSUE TITLE
Customizing design - best practice?

### ISSUE THREAD

**Issue by staceyzav** [salcode/bootstrap-genesis#171]
Hi - First, thanks for the work on this!  This isn't an issue, but rather a pretty basic question.  Where is the best place to add my custom css without disturbing the bootstrap files or theme in case I wish to update later?  I'd prefer to add on a stylesheet than in the dashboard (I know I can add custom css from the theme customizer, but would rather do so on a file in the theme if possible).

Thanks again!

**Comment by salcode** [comment]
Hi @staceyzav,

Thanks for your kind words.  In regards to your question,

> Where is the best place to add my custom css without disturbing the bootstrap files or theme in case I wish to update later?

Your question prompted me to add this page [How to Make CSS Changes to Bootstrap Genesis](https://github.com/salcode/bootstrap-genesis/wiki/How-to-Make-CSS-Changes) to the wiki.

To me, the best practice would be the section on [Using Sass](https://github.com/salcode/bootstrap-genesis/wiki/How-to-Make-CSS-Changes#using-sass).

If you prefer not to use Sass, I think the [Modify Existing CSS](https://github.com/salcode/bootstrap-genesis/wiki/How-to-Make-CSS-Changes#modify-existing-css) would be my next preferred way to modify things.

Finally, if you feel it is imperative to be able to update Bootstrap Genesis, I personally would go the [Add New CSS with a Custom Plugin](https://github.com/salcode/bootstrap-genesis/wiki/How-to-Make-CSS-Changes#add-new-css-with-a-custom-plugin) route.  **Note**: When I build sites, I use Bootstrap Genesis as a starting point and create a new theme from it (with a new name).  I never update Bootstrap Genesis on these sites.  Instead, I update the Genesis parent theme each time to get the necessary updates.

I'm happy to hear you're using Bootstrap Genesis, I hope this helps.

**Comment by staceyzav** [comment]
Thanks for the quick and (thorough) reply and detailed post.  

That all sounds great.  I wasn't sure how imperative it was to update the bootstrap files.  

I've always used Genesis child themes and customized them directly using a similar method, so this sounds great.  I love bootstrap and have often added the column classes to my themes, so I'm excited to try out your theme as a starting point for my sites.  Thanks again!

**Comment by salcode** [comment]
My pleasure.  If you create any sites you'd like to share, there is a [Bootstrap Genesis in the Wild](https://github.com/salcode/bootstrap-genesis/wiki/Bootstrap-Genesis-in-the-Wild) page in the wiki, where I'd love to see more links of sites built using Bootstrap Genesis.
