### ISSUE TITLE
Change media queries

### ISSUE THREAD

**Issue by codenameEli** [salcode/bootstrap-genesis#20]
When/if you upgrade to Bootstrap 3, the media queries will need updated. These are the media queries if you don't want to style the mobile first way.

<code>@media ( min-width: 1200px )</code> -> <code>@media ( min-width: $screen-lg-min )</code>
<code>@media ( max-width: 979px )</code> -> <code>@media ( max-width: $screen-sm-max )</code>
<code>@media ( max-width: 767px )</code> -> <code>@media ( max-width: $screen-xs-max )</code>
<code>@media ( max-width: 480px )</code> -> <code>@media ( max-width: $screen-xs-min )</code>

**Comment by salcode** [comment]
Thanks, we're going to stick with the mobile first default Bootstrap 3 behavior.
