### ISSUE TITLE
Remove duplicate featured images on blog page

### ISSUE THREAD

**Issue by codenameEli** [salcode/bootstrap-genesis#35]
On the backend of WordPress, if you set "Include the Featured Image" under Genesis->Theme Settings, you will get the Genesis Archive Featured Image and the archive-featured-image.

If this setting is enabled, the archive-featured-image should not display. 

Screenshot of setting the image in the backend
![screenshot 2015-02-14 11 41 31](https://cloud.githubusercontent.com/assets/4925333/6200284/8e8aa388-b43e-11e4-94f5-fe4469aaeedf.png)

Screenshot of display on blog page
![screenshot 2015-02-14 11 41 52](https://cloud.githubusercontent.com/assets/4925333/6200285/9a6e7eae-b43e-11e4-956e-527c560f39e9.png)

**Comment by salcode** [comment]
@codenameEli you're right this definitely needs to be improved, thank you for bringing it up.  While I agree your patch makes it better than the current state, I think it can be improved further.

## Current Behavior
Bootstrap Genesis puts the featured image before `.entry-header` regardless of the Genesis Theme Settings (and activating "Include the Featured Image" results in the featured image displayed twice).

## Default Genesis Behavior
Activating "Include the Featured Image" results in the featured image displaying inside `.entry-content` (__after__ the `.entry-header`)

I really prefer the Featured Image before `.entry-header` but agree we should integrate better with Genesis core on this item.

## Possible Options
1.  Disable the Bootstrap Genesis Featured Image if the Genesis Theme Setting "Include the Featured Image" is on.  Definitely an improvement but I think we can integrate even further.
I believe the whole reason we're not using the default behavior is Genesis puts the featured image inside `.entry-content`, which is __after__ the `.entry-header`.

2.  Remove the custom Featured Image functionality and use the default Genesis behavior (again, I'm not a fan of where the Featured Image displays)

3.  __(Recommended)__ We move where the built-in Featured Image displays by unhooking it from displaying in `.entry-content` and instead hooking in before the `.entry-header`.  This way we could still use the Genesis Theme Setting "Include the Featured Image".  



Final note, is it possible you posted the wrong image with your original issue?

**Comment by codenameEli** [comment]
Thanks for the notes, I agree with option 3. I will work on that change and see what I come up with. 
Were you expecting something like this...
![image](https://cloud.githubusercontent.com/assets/4925333/6201210/543c8a8a-b46a-11e4-9095-e335a2c80b08.png)
