### ISSUE TITLE
Bootstrap Menu shouldn't be applied to widgets 

### ISSUE THREAD

**Issue by bryanwillis** [salcode/bootstrap-genesis#44]
The wordpress menu widget shouldn't adopt the bootstrap menu. The container class is being added to widget menus which causes issues because if a widget menu is being used in the primary sidebar for example, the container class is being nested in another container class which isn't good

`<nav class="navbar navbar-default">
    <div class="container-fluid">
    </div>
</nav>`

**Comment by salcode** [comment]
@bryanwillis, I agree this is a good idea, thanks.

Currently, the Bootstrap markup is applied with the custom nav walker __wp_bootstrap_navwalker__.

This is applied in `lib/nav.php` based on the conditional
```
if (
    'primary' === $args['theme_location'] ||
    'secondary' === $args['theme_location']
) {
```

I'm guessing this conditional will need to include a check that the nav is __NOT__ in a widget.

I'm also open to other ideas for implementing this.
