### ISSUE TITLE
Add list of sites built on this theme

### ISSUE THREAD

**Issue by salcode** [salcode/bootstrap-genesis#50]
Would this make sense in the `README.md` file or would the [wiki](https://github.com/salcode/bootstrap-genesis/wiki) make more sense?

**Comment by salcode** [comment]
Add site from #99

**Comment by bryanwillis** [comment]
Finishing up a few right now that I'll post as soon as I get the ok from the company owners. Here's one (http://disputebills.com/) I've been working on for fun for a friend the past few weeks (still got a little work to do, but it's almost there). I've been using ACF plugin as well as Styles Plugin and feel like it's pretty efficient for whipping out themes themes now. Hopefully, I will have some free time this next month and I'll upload a spinoff of BSG that is more of a "preconfigured" variation for the non-nerds out there.

Sal what is your opinion on setting up an organization for this. I feel like we're starting to get a few add-ons / plugins (like the fixed nav for example or logo customizer) with more to come, but nobody really uses them and I'm pretty sure most people don't realize they exist.

Check out roots setup: https://github.com/roots

It seems like setup like this could really help the theme and it's addons grow faster. Anyway, just an idea.

I feel like this theme is on the verge of potentially getting really big if we just do a few things to help it along.

**Comment by salcode** [comment]
@bryanwillis At least for the time being, I've created a [Wiki Page Listing Sites Built with Bootstrap Genesis](https://github.com/salcode/bootstrap-genesis/wiki/Bootstrap-Genesis-in-the-Wild).

Setting up an organization isn't something I've really considered before.  At a minimum, I think we should create a page on the Wiki listing some of the different resources out there.

I don't think I'm interested in creating something the scale of Roots.  I like the idea of sharing this for other people to use but I like the idea of keeping it low friction.  I'll definitely need to give this some more thought.

I look forward to seeing your additional sites.  http://disputebills.com/ certainly looks good :+1:

**Comment by salcode** [comment]
For now, this list of sites appears in the Wiki at [Bootstrap Genesis in the Wild](https://github.com/salcode/bootstrap-genesis/wiki/Bootstrap-Genesis-in-the-Wild)
