### ISSUE TITLE
Remove widget background color?

### ISSUE THREAD

**Issue by salcode** [salcode/bootstrap-genesis#56]
In the screenshot, the right is the current version and the left is without a background color.

I think I prefer it without a background color.

If we do go with this we'll still keep the background-color Sass variable, the default value will be transparent.

![image](https://cloud.githubusercontent.com/assets/5194588/6492591/d151ed32-c282-11e4-9bf6-18727a4e5b06.png)

**Comment by bryanwillis** [comment]
I 100 percent agree. Keeps things cleaner and more generic looking also which is what I think a starter theme should be.

**Comment by salcode** [comment]
Offline conversations also support removing the background color.

@bryanwillis are you interested in doing a PR?  I'd be happy to help if you have any questions.  No big deal if you'd prefer to take a pass on this, I'm just trying to expanding the contributors section.

**Comment by bryanwillis** [comment]
Yea for sure. Just let me know what you want me to do.

**Comment by salcode** [comment]
If I were making a PR for this, my flow would look like
- create a branch from `development` 
- change __$widgetBgColor__ to __transparent__ in `css/sass/supporting/variables.scss`
- in your commit include the words "Fixes #56" (this will automatically close this issue when the code gets merged in)
- push your branch to GitHub
- click the Pull Request button and make the PR with your new branch and `salcode:bootstrap-genesis:develop`

Let me know if you have any questions, I remember PRs being really tricky the first couple of times.

**Comment by bryanwillis** [comment]
Yea I think I tried doing this originally when I was doing the different layout styles, but messed it up. Your example should help. I've been using github for a couple years now, but I've never had much time until recently to figure it all out. I'll try it out tonight when I get a chance.

**Comment by salcode** [comment]
@bryanwillis sorry jumping on this, I'm trying to get some of these issues cleared out.

Thanks for everything you've been adding to this theme (both in PRs and in discussion).
