### ISSUE TITLE
Bootstrap Genesis Graphic w/ Logos

### ISSUE THREAD

**Issue by bryanwillis** [salcode/bootstrap-genesis#64]
This isn't an issue, but I'm not sure where to post general comments. 

I decided to create a [child plugin](https://github.com/bryanwillis/bootstrap-genesis-addons) for myself, adding things I personally want to include when using bootstrap-genesis, but are most likely not "Pull Request" worthy. Basically it's a **"Child Child Theme"** or theme specific plugin, so   I don't have to specifically alter the theme on things I'm not really sure everyone would want. 

Anyway, I had added a simple image with the framework logos. I figured I'd crop off the add-ons part in case you wanted it.

![bootstrap genesis](https://cloud.githubusercontent.com/assets/4042621/6660595/0237beb8-cb6b-11e4-82a0-e5ce683a0502.png)

**Comment by salcode** [comment]
@bryanwillis very cool, thank you.

I've updated the name of this issue to make this graphic easy to find in the future.

I'm looking forward to checking out your plugin.

For future readers of this thread interested in @bryanwillis's plugin, it is online at
https://github.com/bryanwillis/bootstrap-genesis-addons

**Comment by salcode** [comment]
@bryanwillis this is a great graphic and I'm tempted to use it for the `screenshot.png` but I do think there is a lot of value in having the `screenshot.png` show what the theme will look like.  I am going to close this issue but I'm really glad to have this recorded here so I know where to come back to get it.

As long as it is okay with you, I anticipate I'll use this in future blog posts.

Thanks.
