### ISSUE TITLE
Default header can't be removed for landing pages?

### ISSUE THREAD

**Issue by nyxium** [salcode/bootstrap-genesis#86]
Hi,

I am working with your child theme for a couple of days now but I can't manage to remove the header for a landing page. The genesis hooks below seem not to work. The footer can be removed.

remove_action('genesis_header', 'genesis_do_header');
remove_action('genesis_header', 'genesis_header_markup_open', 5);
remove_action('genesis_header', 'genesis_header_markup_close', 15);
remove_action( 'genesis_after_header', 'genesis_do_nav' );

Is this intended, or is there a workaround for this, or am i doing something wrong?

Thx Nick

edit: unregistering the primary menu did the trick

**Comment by salcode** [comment]
I see from your edit you've successfully removed the nav.  To clarify, why you're seeing this behavior.

## Default Genesis
By default both the nav and sub nav appear after the header.  The default 
```
add_action( 'genesis_after_header', 'genesis_do_nav' );
add_action( 'genesis_after_header', 'genesis_do_subnav' );
```

## Bootstrap Genesis Modifications

### Why
In my opinion the Bootstrap nav looks best at the top of the page and thus I've made this the default.

### How
To accomplish this, I'm unhooking the nav and sub_nav from their default position (after the header) and hooking them before the header.  (this all happens in `lib/nav.php`)

## How to Remove the nav and sub_nav from Bootstrap Genesis
These lines will unhook the nav and subnav from their new position.
```
remove_action( 'genesis_before', 'genesis_do_nav' );
remove_action( 'genesis_before', 'genesis_do_subnav' );
```

As you pointed out, unregistering the menu will also work.

**Comment by salcode** [comment]
I'd like to start putting together a list of themes or sites that are using Bootstrap Genesis as a base.  If you'd like to be included, please open a new issue and include your URL when your work goes live.

Thanks.

**Comment by salcode** [comment]
Added Wiki page [Modifications from Default Genesis Hooks](https://github.com/salcode/bootstrap-genesis/wiki/Modifications-from-Default-Genesis-Hooks) for a more accessible resource to address this question in the future

**Comment by nyxium** [comment]
Hi Sal,

Thanks for your quick and clarifying response! I am currently still working on two websites, i will make an issue once they are available for public as suggested.

Cheers,

Nick
