### ISSUE TITLE
Finally our website is live

### ISSUE THREAD

**Issue by nyxium** [salcode/bootstrap-genesis#99]
Hi,

After completely redoing our corporate identity, due to a name change, I finished our website yesterday. It is finally live at http://expatcity.nl. It is based on the bootstrap genesis theme with some changes here and there. It is yet the biggest and most advanced website I have ever made.

It was really fun to build this website, combining the power of genesis and bootstrap. Now we can work on the acquisition and get our company off the ground :)

Greetings, Nick

**Comment by salcode** [comment]
Congrats!  Looks great.

Thanks for sharing.

**Comment by bryanwillis** [comment]
Wow really nice @nyxium. You definitely took the theme to the next level.

**Comment by nyxium** [comment]
Thanks Sal and Bryan! Really appreciate it.

**Comment by salcode** [comment]
Added to https://github.com/salcode/bootstrap-genesis/wiki/Bootstrap-Genesis-in-the-Wild
